#!/usr/bin/env node
/**
 * Generate a single generated/types.ts from all JSON Schema files.
 * Runs json2ts on each schema individually and concatenates output.
 */

import { execSync } from "child_process";
import { readdirSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname, basename } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SCHEMA_DIR = resolve(ROOT, "jsonschema");
const OUTPUT = resolve(ROOT, "generated", "types.ts");
const JSON2TS = resolve(ROOT, "node_modules", ".bin", "json2ts");

mkdirSync(resolve(ROOT, "generated"), { recursive: true });

const schemas = readdirSync(SCHEMA_DIR)
  .filter((f) => f.endsWith(".schema.json"))
  .sort();

let combined =
  "// AUTO-GENERATED — do not edit manually\n" +
  "// Source: Core/contracts/jsonschema/*.schema.json\n" +
  "// Generated by: pnpm run build\n\n";

for (const schema of schemas) {
  const schemaPath = resolve(SCHEMA_DIR, schema);
  try {
    const output = execSync(
      `${JSON2TS} --input "${schemaPath}" --unreachableDefinitions`,
      { encoding: "utf-8" }
    );
    combined +=
      `// ─── ${basename(schema)} ───────────────────────────────\n` +
      output +
      "\n";
    console.log(`  ✓ ${schema}`);
  } catch (err) {
    console.error(`  ✗ ${schema}: ${err.message}`);
    process.exit(1);
  }
}

writeFileSync(OUTPUT, combined, "utf-8");
console.log(`\nGenerated: ${OUTPUT} (${combined.split("\n").length} lines)`);
